#!/bin/bash
# This script creates a .gitignore file for a Rust project,
# including rules for build artifacts and disk images.

# Navigate to the project root to ensure correct placement.
# This assumes the script is run from inside the thatte-starter directory.
# For robustness, we could use a more absolute path if needed, but this should suffice.

# Create the .gitignore file with recommended rules.
cat > .gitignore << EOF
# Generated by Gemini for the THATTE project.

# Rust build artifacts
# --------------------
# This is the main directory for all compilation outputs.
/target/

# Disk Images and Boot Files
# --------------------------
# Ignore common disk image formats and UEFI files generated by the build.
*.efi
*.img
*.iso
*.vdi
*.vmdk
*.qcow2

# Toolchain and IDE files
# -----------------------
# Rust Analyzer caches and metadata
/.rust-analyzer/
# VS Code specific settings
/.vscode/

# Operating System files
# ----------------------
# macOS
.DS_Store
# Windows Thumbnail cache
Thumbs.db
# Linux backup files
*~

# Miscellaneous
# -------------
# Log files
*.log
EOF

echo "The .gitignore file has been updated to include disk images."