[package]
name = "hello-compositor-fb"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
nix = { version = "0.29", default-features = false, features = ["fs", "mman"] }
