[package]
name = "thatte-boot-efi"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = "0.28"

# Build an executable for the UEFI target. Cargo will output .efi.
[[bin]]
name = "thatte-boot-efi"
path = "src/main.rs"

# (Optional — keep profiles in the WORKSPACE root to avoid the warning)
